apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverse-words
  name: reverse-words
spec:
  template:
    spec:
      containers:
      - env:
        - name: RELEASE
          value: Stage Release
        - $patch: replace
        image: quay.io/fmoss/tekton-reversewords:505ff5d414b178a77d3c3f4c26742435702401af
        name: reverse-words
